
### Unsafe
GET http://localhost:3001/?site=https://tiktok.com

### Safe
GET http://localhost:3001/?site=https://google.com
  
### Invalid
GET http://localhost:3001/?site=delfi.com

### Invalid
GET http://localhost:3001/?site=delficom

## Tests
### Unsafe
GET http://localhost:3001/?site=https://nudity.testcategory.com

### Unsafe
GET http://localhost:3001/?site=https://www.internetbadguys.com
